In [17]:
import numpy as np
vec = np.array([1,2,3,4,5,6])
#перевернуть массив
print(vec[::-1])

[6 5 4 3 2 1]


In [18]:
#максимальный нечетный элемент
print(max(vec[vec % 2!= 0]))


5


In [19]:
vec[vec % 2!=0] = 3
print(vec)

[3 2 3 4 3 6]


In [20]:
n=20
vec = np.arange(1,n,2)
print(vec)

[ 1  3  5  7  9 11 13 15 17 19]


In [47]:
x = 1.3
vec = np.array([4,1,2,4,5,3])
print(vec)
vec2 = np.abs(vec-x)
print(vec[vec2.argmin()],vec[vec2.argmax()])

[4 1 2 4 5 3]
1 5


In [48]:
vec = np.array([4,6,0,1])
for i in range(vec.size):
    vec[i]/=vec.size-i

vec = np.append(vec,5)
print(vec)

[1 2 0 1 5]


In [50]:
vec = np.array([1,2, 0,1,5])
for i in range(vec.size):
    vec[i]*=vec.size-(i+1)
vec=vec[:-1]
print(vec)

[4 6 0 1]
